# Generated by Django 3.1 on 2024-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'sn_details',
                'managed': True,
            },
        ),
    ]
